# Generated by Django 6.0.2 on 2026-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentclass_alter_student_current_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Alumni', 'Alumni'), ('Transferred', 'Transferred')], default='Active', max_length=20),
        ),
    ]
