# Generated by Django 6.0.2 on 2026-03-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_promotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Board / Affiliation body name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='current_academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2025-2026', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='established_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_assets/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='principal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short motto or tagline for the school.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='vice_principal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='name',
            field=models.CharField(default='School Name', max_length=200),
        ),
    ]
