# Generated by Django 6.0.2 on 2026-03-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_attendancerecord_id_alter_attendancesession_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('current_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('higher_education_info', models.TextField(blank=True, help_text='Details about university or college attended after graduation.', null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('Low', 'Low - Warning'), ('Medium', 'Medium - Detention/Call'), ('High', 'High - Suspension/Expulsion'), ('Positive', 'Positive - Award/Commendation')], default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.student')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
    ]
