# Generated by Django 6.0.2 on 2026-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_lessonplan_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rfid_tag',
            field=models.CharField(blank=True, help_text='Biometric/RFID Tag ID for automated attendance', max_length=100, null=True, unique=True),
        ),
    ]
