# Generated by Django 6.0.2 on 2026-03-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_onlinepaymenttransaction'),
        ('students', '0014_alumniprofile_disciplinaryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymenttransaction',
            name='fee_payment',
        ),
        migrations.AddField(
            model_name='onlinepaymenttransaction',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to='students.feetype'),
        ),
        migrations.AddField(
            model_name='onlinepaymenttransaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to='students.student'),
        ),
    ]
