# Generated by Django 6.0.2 on 2026-03-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='deductions',
            new_name='fixed_deductions',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid_leave',
            field=models.BooleanField(default=True, help_text='Uncheck if this is Leave Without Pay (LWP)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='provident_fund_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
