# Generated by Django 6.0.2 on 2026-02-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_roles', 'Can manage roles and permissions'), ('manage_users', 'Can manage system users'), ('view_dashboard_stats', 'Can view dashboard statistics'), ('manage_academic_settings', 'Can manage classes, subjects, and exams'), ('manage_finances', 'Can manage fees and staff salaries')]},
        ),
    ]
