# Generated by Django 6.0.2 on 2026-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('target_audience', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Teachers', 'Teachers'), ('Staff', 'Staff')], default='All', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
