# Generated by Django 5.1.5 on 2026-03-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0012_alter_attendancerecord_id_alter_attendancesession_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room Name or Number (e.g., Room 101)', max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students this room can hold for an exam')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, help_text='Specific seat designation (optional)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='students.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='exam_seat_plan.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_seats', to='students.student')),
            ],
            options={
                'ordering': ['room', 'seat_number', 'student'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
